"""Color name to HEX resolver service."""

COLOR_MAP = {
    "aliceblue": "#F0F8FF",
    "antiquewhite": "#FAEBD7",
    "aqua": "#00FFFF",
    "aquamarine": "#7FFFD4",
    "azure": "#F0FFFF",
    "beige": "#F5F5DC",
    "bisque": "#FFE4C4",
    "black": "#000000",
    "blanchedalmond": "#FFEBCD",
    "blue": "#0000FF",
    "blueviolet": "#8A2BE2",
    "brown": "#A52A2A",
    "burlywood": "#DEB887",
    "cadetblue": "#5F9EA0",
    "chartreuse": "#7FFF00",
    "chocolate": "#D2691E",
    "coral": "#FF7F50",
    "cornflowerblue": "#6495ED",
    "cornsilk": "#FFF8DC",
    "crimson": "#DC143C",
    "cyan": "#00FFFF",
    "darkblue": "#00008B",
    "darkcyan": "#008B8B",
    "darkgoldenrod": "#B8860B",
    "darkgray": "#A9A9A9",
    "darkgrey": "#A9A9A9",
    "darkgreen": "#006400",
    "darkkhaki": "#BDB76B",
    "darkmagenta": "#8B008B",
    "darkolivegreen": "#556B2F",
    "darkorange": "#FF8C00",
    "darkorchid": "#9932CC",
    "darkred": "#8B0000",
    "darksalmon": "#E9967A",
    "darkseagreen": "#8FBC8F",
    "darkslateblue": "#483D8B",
    "darkslategray": "#2F4F4F",
    "darkslategrey": "#2F4F4F",
    "darkturquoise": "#00CED1",
    "darkviolet": "#9400D3",
    "deeppink": "#FF1493",
    "deepskyblue": "#00BFFF",
    "dimgray": "#696969",
    "dimgrey": "#696969",
    "dodgerblue": "#1E90FF",
    "firebrick": "#B22222",
    "floralwhite": "#FFFAF0",
    "forestgreen": "#228B22",
    "fuchsia": "#FF00FF",
    "gainsboro": "#DCDCDC",
    "ghostwhite": "#F8F8FF",
    "gold": "#FFD700",
    "goldenrod": "#DAA520",
    "gray": "#808080",
    "grey": "#808080",
    "green": "#008000",
    "greenyellow": "#ADFF2F",
    "honeydew": "#F0FFF0",
    "hotpink": "#FF69B4",
    "indianred": "#CD5C5C",
    "indigo": "#4B0082",
    "ivory": "#FFFFF0",
    "khaki": "#F0E68C",
    "lavender": "#E6E6FA",
    "lavenderblush": "#FFF0F5",
    "lawngreen": "#7CFC00",
    "lemonchiffon": "#FFFACD",
    "lightblue": "#ADD8E6",
    "lightcoral": "#F08080",
    "lightcyan": "#E0FFFF",
    "lightgoldenrodyellow": "#FAFAD2",
    "lightgray": "#D3D3D3",
    "lightgrey": "#D3D3D3",
    "lightgreen": "#90EE90",
    "lightpink": "#FFB6C1",
    "lightsalmon": "#FFA07A",
    "lightseagreen": "#20B2AA",
    "lightskyblue": "#87CEFA",
    "lightslategray": "#778899",
    "lightslategrey": "#778899",
    "lightsteelblue": "#B0C4DE",
    "lightyellow": "#FFFFE0",
    "lime": "#00FF00",
    "limegreen": "#32CD32",
    "linen": "#FAF0E6",
    "magenta": "#FF00FF",
    "maroon": "#800000",
    "mediumaquamarine": "#66CDAA",
    "mediumblue": "#0000CD",
    "mediumorchid": "#BA55D3",
    "mediumpurple": "#9370DB",
    "mediumseagreen": "#3CB371",
    "mediumslateblue": "#7B68EE",
    "mediumspringgreen": "#00FA9A",
    "mediumturquoise": "#48D1CC",
    "mediumvioletred": "#C71585",
    "midnightblue": "#191970",
    "mintcream": "#F5FFFA",
    "mistyrose": "#FFE4E1",
    "moccasin": "#FFE4B5",
    "navajowhite": "#FFDEAD",
    "navy": "#000080",
    "oldlace": "#FDF5E6",
    "olive": "#808000",
    "olivedrab": "#6B8E23",
    "orange": "#FFA500",
    "orangered": "#FF4500",
    "orchid": "#DA70D6",
    "palegoldenrod": "#EEE8AA",
    "palegreen": "#98FB98",
    "paleturquoise": "#AFEEEE",
    "palevioletred": "#DB7093",
    "papayawhip": "#FFEFD5",
    "peachpuff": "#FFDAB9",
    "peru": "#CD853F",
    "pink": "#FFC0CB",
    "plum": "#DDA0DD",
    "powderblue": "#B0E0E6",
    "purple": "#800080",
    "red": "#FF0000",
    "rosybrown": "#BC8F8F",
    "royalblue": "#4169E1",
    "saddlebrown": "#8B4513",
    "salmon": "#FA8072",
    "sandybrown": "#F4A460",
    "seagreen": "#2E8B57",
    "seashell": "#FFF5EE",
    "sienna": "#A0522D",
    "silver": "#C0C0C0",
    "skyblue": "#87CEEB",
    "slateblue": "#6A5ACD",
    "slategray": "#708090",
    "slategrey": "#708090",
    "snow": "#FFFAFA",
    "springgreen": "#00FF7F",
    "steelblue": "#4682B4",
    "tan": "#D2B48C",
    "teal": "#008080",
    "thistle": "#D8BFD8",
    "tomato": "#FF6347",
    "turquoise": "#40E0D0",
    "violet": "#EE82EE",
    "wheat": "#F5DEB3",
    "white": "#FFFFFF",
    "whitesmoke": "#F5F5F5",
    "yellow": "#FFFF00",
    "yellowgreen": "#9ACD32",
    "mint": "#98FF98",
    "mint green": "#98FF98",
    "mintgreen": "#98FF98",
    "wine": "#722F37",
    "mustard": "#FFDB58",
    "charcoal": "#36454F",
    "cream": "#FFFDD0",
    "peach": "#FFE5B4",
    "royal blue": "#4169E1",
    "royalblue": "#4169E1",
    "sky blue": "#87CEEB",
    "navy blue": "#000080",
    "navyblue": "#000080",
    "baby blue": "#89CFF0",
    "babyblue": "#89CFF0",
    "rose": "#FF007F",
    "ruby": "#E0115F",
    "sapphire": "#0F52BA",
    "emerald": "#50C878",
    "amber": "#FFBF00",
    "mauve": "#E0B0FF",
    "lilac": "#C8A2C8",
    "burgundy": "#800020",
    "taupe": "#483C32",
    "terracotta": "#E2725B",
    "denim": "#1560BD",
    "blush": "#DE5D83",
    "ivory": "#FFFFF0",
    "ebony": "#555D50",
    "copper": "#B87333",
    "bronze": "#CD7F32",
    "steel": "#4682B4",
    "slate": "#708090",
    "mocha": "#967969",
    "caramel": "#FFD59A",
    "vanilla": "#F3E5AB",
    "cinnamon": "#D2691E",
    "honey": "#FFC30B",
    "lemon": "#FFF700",
    "lime": "#00FF00",
    "forest": "#228B22",
    "army": "#4B5320",
    "hunter": "#355E3B",
    "jade": "#00A86B",
    "sage": "#BCB88A",
    "olive": "#808000",
    "avocado": "#568203",
    "clover": "#007F00",
    "fern": "#4F7942",
    "celeste": "#B2FFFF",
    "indigo": "#4B0082",
    "violet": "#EE82EE",
    "fuchsia": "#FF00FF",
    "magenta": "#FF00FF",
    "cerise": "#DE3163",
    "raspberry": "#E30B5D",
    "strawberry": "#FC5A8D",
    "cherry": "#DE3163",
    "cranberry": "#9B1B30",
    "watermelon": "#FC6C85",
    "apricot": "#FBCEB1",
    "tangerine": "#FF9966",
    "pumpkin": "#FF7518",
    "ginger": "#B06500",
    "rust": "#B7410E",
    "mahogany": "#C04000",
    "chestnut": "#954535",
    "hazelnut": "#B87333",
    "almond": "#EED9C4",
    "walnut": "#773F1A",
    "pecan": "#AC8042",
    "chocolate": "#D2691E",
    "cocoa": "#D2691E",
    "coffee": "#6F4E37",
    "espresso": "#612718",
    "latte": "#C5A582",
    "mocha": "#967969",
    "cappuccino": "#9E7869",
    "teal": "#008080",
    "cyan": "#00FFFF",
    "aqua": "#00FFFF",
    "cerulean": "#007BA7",
    "ultramarine": "#120A8F",
    "azure": "#F0FFFF",
    "cobalt": "#0047AB",
    "periwinkle": "#CCCCFF",
    "lavender": "#E6E6FA",
    "lilac": "#C8A2C8",
    "wisteria": "#C9A0DC",
    "amethyst": "#9966CC",
    "plum": "#DDA0DD",
    "orchid": "#DA70D6",
    "eggplant": "#614051",
    "aubergine": "#614051",
}

ALIAS_MAP = {
    "grey": "gray",
    "dark grey": "darkgray",
    "dark gray": "darkgray",
    "light grey": "lightgray",
    "light gray": "lightgray",
    "slate grey": "slategray",
    "slate gray": "slategray",
    "dim grey": "dimgray",
    "dim gray": "dimgray",
    "dark slate": "darkslategray",
    "dark slate gray": "darkslategray",
    "dark slate grey": "darkslategray",
    "light slate": "lightslategray",
    "light slate gray": "lightslategray",
    "light slate grey": "lightslategray",
    "aqua": "cyan",
    "fuchsia": "magenta",
}


class ColorResolver:
    def __init__(self):
        self._lookup = {}
        for name, hex_val in COLOR_MAP.items():
            self._lookup[self._normalize(name)] = hex_val.upper()

    def _normalize(self, name: str) -> str:
        return " ".join(name.strip().lower().split())

    def resolve(self, name: str) -> str | None:
        normalized = self._normalize(name)
        if normalized in self._lookup:
            return self._lookup[normalized]
        if normalized in ALIAS_MAP:
            target = self._normalize(ALIAS_MAP[normalized])
            if target in self._lookup:
                return self._lookup[target]
        return None

    def get_all_colors(self) -> list[dict]:
        seen = set()
        result = []
        for name, hex_val in COLOR_MAP.items():
            normalized = self._normalize(name)
            if normalized not in seen:
                seen.add(normalized)
                display_name = " ".join(w.capitalize() for w in name.split())
                result.append({"name": display_name, "hex": hex_val.upper()})
        return sorted(result, key=lambda x: x["name"].lower())


resolver = ColorResolver()
