"""create custom_products table

Revision ID: 9989daa8d9aa
Revises: 88171fe87ea7
Create Date: 2026-06-22 03:56:12.201733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9989daa8d9aa'
down_revision: Union[str, None] = '88171fe87ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('collection', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('image_front', sa.String(length=500), nullable=True),
    sa.Column('image_back', sa.String(length=500), nullable=True),
    sa.Column('image_size_chart', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', sa.JSON(), nullable=True),
    sa.Column('original_price_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_price_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='custom_product_status_enum'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=True),
    sa.Column('is_best_seller', sa.Boolean(), nullable=True),
    sa.Column('is_new_arrival', sa.Boolean(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_products_category_id'), 'custom_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_custom_products_collection_id'), 'custom_products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_custom_products_deleted_at'), 'custom_products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_custom_products_id'), 'custom_products', ['id'], unique=False)
    op.create_index(op.f('ix_custom_products_is_best_seller'), 'custom_products', ['is_best_seller'], unique=False)
    op.create_index(op.f('ix_custom_products_is_featured'), 'custom_products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_custom_products_is_new_arrival'), 'custom_products', ['is_new_arrival'], unique=False)
    op.create_index(op.f('ix_custom_products_is_trending'), 'custom_products', ['is_trending'], unique=False)
    op.create_index(op.f('ix_custom_products_sku'), 'custom_products', ['sku'], unique=True)
    op.create_index(op.f('ix_custom_products_slug'), 'custom_products', ['slug'], unique=True)
    op.create_index(op.f('ix_custom_products_status'), 'custom_products', ['status'], unique=False)
    # op.alter_column('banners', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_server_default=sa.text('0'))
    # op.alter_column('banners', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('true'))
    # op.drop_constraint('uq_categories_slug', 'categories', type_='unique')
    # op.drop_constraint('uq_collections_slug', 'collections', type_='unique')
    # op.drop_index('ix_customers_email_trgm', table_name='customers', postgresql_using='gin')
    # op.drop_index('ix_customers_first_name_trgm', table_name='customers', postgresql_using='gin')
    # op.drop_index('ix_customers_is_active', table_name='customers')
    # op.drop_index('ix_customers_last_name_trgm', table_name='customers', postgresql_using='gin')
    # op.alter_column('offers', 'status',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=True,
    #            existing_server_default=sa.text("'saved'::character varying"))
    # op.drop_index('ix_offers_status', table_name='offers')
    # op.alter_column('orders', 'customer_name',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('orders', 'product_name',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('product_variants', 'sku',
    #            existing_type=sa.VARCHAR(length=120),
    #            type_=sa.String(length=100),
    #            existing_nullable=False)
    # op.alter_column('product_variants', 'color',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('product_variants', 'discount_percentage',
    #            existing_type=sa.NUMERIC(precision=5, scale=2),
    #            nullable=True)
    # op.alter_column('product_variants', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('product_variants', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.drop_index('ix_product_variants_color', table_name='product_variants')
    # op.drop_index('ix_product_variants_size', table_name='product_variants')
    # op.drop_index('ix_product_variants_stock_quantity', table_name='product_variants')
    # op.drop_index('ix_variant_product_stock', table_name='product_variants')
    # op.drop_index('ix_variants_sku_trgm', table_name='product_variants', postgresql_using='gin')
    # op.alter_column('products', 'collection',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('products', 'tags',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=True)
    # op.alter_column('products', 'is_featured',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # op.alter_column('products', 'is_trending',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('products', 'is_best_seller',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('products', 'is_new_arrival',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('products', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('products', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.drop_index('ix_products_collection', table_name='products')
    # op.drop_index('ix_products_collection_trgm', table_name='products', postgresql_using='gin')
    # op.drop_index('ix_products_created_at', table_name='products')
    # op.drop_index('ix_products_deleted_status_created', table_name='products')
    # op.drop_index('ix_products_slug_trgm', table_name='products', postgresql_using='gin')
    # op.drop_index('ix_products_title_trgm', table_name='products', postgresql_using='gin')
    # op.drop_index('uq_products_slug_active', table_name='products', postgresql_where='(deleted_at IS NULL)')
    # op.drop_index('ix_products_slug', table_name='products')
    # op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_custom_products_status'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_slug'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_sku'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_is_trending'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_is_new_arrival'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_is_featured'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_is_best_seller'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_id'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_deleted_at'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_collection_id'), table_name='custom_products')
    op.drop_index(op.f('ix_custom_products_category_id'), table_name='custom_products')

    op.drop_table('custom_products')