"""orders update

Revision ID: dee988a94348
Revises: ae78e3561c2b
Create Date: 2026-06-08 14:05:42.684158

FIX C-2: Added delivery_days and expected_delivery_date columns.
These are present in the Order ORM model but were missing from this
migration, causing "column does not exist" PostgreSQL errors on
every POST /orders/ call on a fresh deployment.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dee988a94348'
down_revision: Union[str, None] = "ae78e3561c2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     'orders',
    #     sa.Column('customer_name', sa.String(length=255), nullable=True)
    # )
    # op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    # op.add_column('orders', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    # op.add_column('orders', sa.Column('address_line1', sa.String(length=255), nullable=True))
    # op.add_column('orders', sa.Column('address_line2', sa.String(length=255), nullable=True))
    # op.add_column('orders', sa.Column('city', sa.String(length=100), nullable=True))
    # op.add_column('orders', sa.Column('state', sa.String(length=100), nullable=True))
    # op.add_column('orders', sa.Column('country', sa.String(length=100), nullable=True))
    # op.add_column('orders', sa.Column('pincode', sa.String(length=20), nullable=True))
    # op.add_column(
    #     'orders',
    #     sa.Column('product_name', sa.String(length=255), nullable=True)
    # )
    # op.add_column('orders', sa.Column('product_image', sa.String(length=500), nullable=True))
    # op.add_column('orders', sa.Column('size', sa.String(length=50), nullable=True))
    # op.add_column('orders', sa.Column('color', sa.String(length=100), nullable=True))
    # op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    # op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))
    # op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    # op.add_column('orders', sa.Column('tracking_status', sa.String(length=50), nullable=True))
    # op.add_column('orders', sa.Column('tracking_note', sa.Text(), nullable=True))
    # op.alter_column('orders', 'order_number',
    #            existing_type=sa.VARCHAR(length=32),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    # op.alter_column('orders', 'ordered_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('orders', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('orders', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    # op.drop_column('orders', 'customer')
    # op.drop_column('orders', 'total')
    # op.drop_column('orders', 'status')
    # op.drop_column('orders', 'items')
    # op.drop_column('orders', 'payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FIX C-2: Drop the two added columns on rollback
    op.drop_column('orders', 'expected_delivery_date')
    op.drop_column('orders', 'delivery_days')

    op.add_column('orders', sa.Column('payment', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'ordered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'order_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('orders', 'tracking_note')
    op.drop_column('orders', 'tracking_status')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'color')
    op.drop_column('orders', 'size')
    op.drop_column('orders', 'product_image')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'pincode')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'address_line2')
    op.drop_column('orders', 'address_line1')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###